# Generated by Django 6.0.5 on 2026-05-13 15:11

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('titre', models.CharField(help_text="Titre ou numéro d'identification de la chambre", max_length=200, verbose_name='Titre')),
                ('type_chambre', models.CharField(choices=[('simple', 'Chambre simple'), ('double', 'Chambre double'), ('studio', 'Studio'), ('appartement', 'Appartement')], help_text='Type de logement (simple, double, studio, appartement)', max_length=20, verbose_name='Type de chambre')),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la chambre (optionnelle)', null=True, verbose_name='Description')),
                ('prix_mensuel', models.DecimalField(decimal_places=2, help_text='Montant du loyer par mois', max_digits=10, verbose_name='Prix mensuel (FCFA)')),
                ('superficie', models.FloatField(blank=True, help_text='Surface au sol en mètres carrés (optionnelle)', null=True, verbose_name='Superficie (m²)')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupee', 'Occupée'), ('suspendue', 'Suspendue')], default='disponible', help_text='État actuel de la chambre (disponible, occupée, suspendue)', max_length=20, verbose_name='Statut')),
                ('wifi', models.BooleanField(default=False, help_text='Cocher si la connexion Wi-Fi est fournie', verbose_name='Wi-Fi inclus')),
                ('electricite', models.BooleanField(default=True, help_text="Cocher si l'électricité est disponible", verbose_name='Électricité')),
                ('eau_courante', models.BooleanField(default=True, help_text="Cocher si l'eau courante est disponible", verbose_name='Eau courante')),
                ('cuisine', models.BooleanField(default=False, help_text="Cocher si la chambre dispose d'une cuisine", verbose_name='Cuisine équipée')),
                ('salle_de_bain', models.BooleanField(default=False, help_text='Cocher si une salle de bain est attenante', verbose_name='Salle de bain privée')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('nom', models.CharField(help_text='Nom de la ville', max_length=200, verbose_name='Nom de la ville')),
                ('adresse', models.TextField(blank=True, help_text='Adresse de la ville', null=True, verbose_name='Adresse')),
                ('quartier', models.CharField(help_text='Quartier de la ville', max_length=100, verbose_name='Quartier')),
                ('ville', models.CharField(default='Bandjoun', help_text='Ville', max_length=100, verbose_name='Ville')),
                ('description', models.TextField(blank=True, help_text='Description de la ville', null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoChambre',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('image', models.ImageField(help_text='Fichier image de la chambre (format JPG, PNG)', upload_to='chambres/', verbose_name='Image')),
                ('principale', models.BooleanField(default=False, help_text='Cocher si cette photo doit être affichée en premier', verbose_name='Photo principale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoCity',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('image', models.ImageField(help_text='Fichier image de la cité (format JPG, PNG)', upload_to='chambres/', verbose_name='Image')),
                ('principale', models.BooleanField(default=False, help_text='Cocher si cette photo doit être affichée en premier', verbose_name='Photo principale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('date_debut', models.DateField(help_text="Date d'entrée prévue", verbose_name='Date de début')),
                ('date_fin', models.DateField(help_text='Date de sortie prévue', verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', help_text='État de la réservation (en attente, confirmée, annulée, terminée)', max_length=20, verbose_name='Statut')),
                ('message', models.TextField(blank=True, help_text='Message ou demande particulière (optionnel)', null=True, verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
