# Generated by Django 6.0.5 on 2026-05-13 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avis',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='core.chambre'),
        ),
        migrations.AddField(
            model_name='cite',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chambre',
            name='cite',
            field=models.ForeignKey(help_text='Cité à laquelle appartient la chambre', on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='core.cite', verbose_name='Cité'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='photo_chambre',
            field=models.ManyToManyField(blank=True, help_text='Photos de la chambre', null=True, to='core.photochambre', verbose_name='Photos'),
        ),
        migrations.AddField(
            model_name='cite',
            name='photo_cite',
            field=models.ManyToManyField(blank=True, null=True, to='core.photocity'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='chambre',
            field=models.ForeignKey(help_text='Chambre réservée', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.chambre', verbose_name='Chambre'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='etudiant',
            field=models.ForeignKey(help_text='Utilisateur (étudiant) qui effectue la réservation', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('etudiant', 'chambre')},
        ),
    ]
